# regex --- 匹配正则表达式模式：^ {pattern} $
# lowercase --- 每个字母必须小写 忽略非字母
# camelcase --- camelCase --- 字符串必须为camelCase 只允许使用字母和数字
# pascalcase --- PascalCase --- 字符串必须为Pascalcase 只允许使用字母和数字
# snakecase --- snake_case --- 字符串必须为snake_case 只允许使用小写字母，数字和_
# screamingsnakecase --- SCREAMING_SNAKE_CASE --- 字符串必须是 snake_case 的全大写风格 只允许使用大写字母，数字和_
# kebabcase --- kebab-case --- 字符串必须为kebab-case 仅小写字母，数字和-允许
# pointcase --- point.case ---字符串必须为“小写” 仅小写字母，数字和.允许的
ls:
    src/*:
        .js: camelCase
        .vue: PascalCase | regex:^index
        .ts: camelCase
        .tsx: PascalCase | camelCase
        .d.ts: camelCase
        .mock.ts: kebab-case | camelCase
        .data.ts: kebab-case | camelCase
        .test-d.ts: kebab-case
        .less: camelCase | pointcase
        .spec.ts: camelCase | PascalCase
    src/{views}/*:
        .dir: regex:[A-Z]+[a-zA-Z0-9]* | regex:^components | regex:^hooks? | regex:^use.+ | regex:^types? | regex:^servers? | regex:^apis? | regex:^src

ignore:
    - node_modules
    - .git
    - .circleci
    - .github
    - .vscode
    - .idea
    - dist
    - .local
    - .husky
    - src/locales/lang
