/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    Charts: typeof import('./../src/components/Charts/index.vue')['default']
    Empty: typeof import('./../src/components/Empty/index.vue')['default']
    MessageBox: typeof import('./../src/components/MessageBox/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.tsx')['default']
  }
}
