export interface LoginParams {
    loginName: string
    password: string
    code: string
    uuid: string
}

export interface UserInfoData {
    createBy: string
    createTime: string
    updateBy: string
    updateTime: string
    remark: string
    tenantId: string
    userId: string
    deptId: string
    deptName: string
    loginName: string
    userName: string
    tenantName: string
    userType: string
    appName: string
    email: string
    unionId: string
    openId: string
    infoId: string
    phonenumber: string
    sex: string
    avatar: string
    city: string
    password: string
    superMan: string
    status: string
    delFlag: string
    loginIp: string
    loginDate: string
    pwdUpdateDate: string
    tokenId: string
    uuid: string
    platform: string
    pid: string
    accountType: string
    accountNum: string
    shareType: string
    selfAccount: string
    openSystem: string
    userList: string
    isUpdateSupport: string
    operName: string
    wechatPhoneNumber: string
    douyinPhoneNumber: string
    customerType: string
    salt: string
    userCode: string
    appInfoCode: string
    environment: string
    appId: string
    userCount: string
    openWechat: number
    openDouyin: number
    readWriteType: number
    roleKeys: string[]
    packageIdList: string
    dept: string
    roles: any[]
    roleIds: string
    postIds: string
    mapUserId: string
    appCode: string
    ids: string
    tableSupport: string
    areaName: string
    profile: string
    code: string
    wechatNumber: string
    wechatQrCode: string
    roleName: string
    roleId: string
    storeName: string
    admin: boolean
}
